# Generated by Django 5.2.1 on 2025-05-25 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden']},
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='ansiedad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='autoestima',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='depresion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='estres',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='puntuacion_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('AN', 'Ansiedad'), ('DE', 'Depresión'), ('ES', 'Estrés'), ('AU', 'Autoestima')], default='AN', max_length=2, verbose_name='Tipo de pregunta'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='recomendaciones',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(verbose_name='Texto de la pregunta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pregunta'),
        ),
    ]
