# Generated by Django 5.2.1 on 2025-05-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_evaluacion_options_alter_pregunta_options_and_more'),
    ]

    operations = [
    ]
