# Generated by Django 5.2.1 on 2025-05-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250525_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='ansiedad',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='autoestima',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='depresion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='estres',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='recomendaciones',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='mensaje_personalizado',
            field=models.TextField(default='Evaluación en proceso', help_text='Mensaje generado según los resultados'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nivel_actual',
            field=models.IntegerField(choices=[(1, 'Requiere atención profesional inmediata'), (2, 'Necesita mejorar significativamente'), (3, 'Estado regular con áreas a mejorar'), (4, 'Buen estado con pequeños ajustes'), (5, 'Excelente estado emocional')], default=3, help_text='Nivel calculado basado en las respuestas'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(choices=[('EM', 'Emociones'), ('HB', 'Hábitos'), ('EN', 'Energía'), ('CO', 'Comportamiento'), ('RE', 'Relaciones')], default='EM', help_text='Categoría a la que pertenece la pregunta', max_length=2),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='puntuacion_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='valor',
            field=models.IntegerField(help_text='Escala del 1 al 5'),
        ),
    ]
