# Generated by Django 5.2.1 on 2025-05-26 01:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_evaluacion_options_alter_respuesta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'get_latest_by': 'fecha', 'ordering': ['-fecha'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['-fecha', 'pregunta__orden'], 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='analisis_categorias',
            field=models.JSONField(default=dict, help_text='Detalles del resultado por categoría', verbose_name='Análisis por categorías'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='respuestas',
            field=models.ManyToManyField(related_name='evaluaciones', to='main.respuesta', verbose_name='Respuestas asociadas'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluación'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='mensaje_personalizado',
            field=models.TextField(verbose_name='Mensaje personalizado'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='nivel_actual',
            field=models.IntegerField(choices=[(1, 'Requiere atención profesional inmediata'), (2, 'Necesita mejorar significativamente'), (3, 'Estado regular con áreas a mejorar'), (4, 'Buen estado con pequeños ajustes'), (5, 'Excelente estado emocional')], verbose_name='Nivel actual'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='puntuacion_total',
            field=models.FloatField(help_text='Promedio de todas las respuestas', verbose_name='Puntuación total'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(choices=[('EM', 'Emociones'), ('HB', 'Hábitos'), ('EN', 'Energía'), ('CO', 'Comportamiento'), ('RE', 'Relaciones')], default='EM', max_length=2, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.PositiveIntegerField(unique=True, verbose_name='Orden de aparición'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(verbose_name='Texto de la pregunta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='main.pregunta', verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='valor',
            field=models.IntegerField(help_text='Escala del 1 (peor) al 5 (mejor)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Valor de respuesta'),
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('usuario', 'pregunta', 'fecha')},
        ),
    ]
