# Generated by Django 5.2.1 on 2025-05-26 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_evaluacion_options_alter_pregunta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='respuestas',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='main.evaluacion', verbose_name='Evaluación asociada'),
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('usuario', 'pregunta', 'evaluacion')},
        ),
    ]
