# Generated by Django 5.2.1 on 2025-05-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_respuesta_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(choices=[('EM', 'Emociones'), ('HB', 'Hábitos'), ('EN', 'Energía'), ('CO', 'Comportamiento'), ('RE', 'Relaciones'), ('PE', 'Pensamiento y perspectiva'), ('ES', 'Estres y Manejo')], default='EM', max_length=2, verbose_name='Categoría'),
        ),
    ]
