# Generated by Django 5.2.1 on 2025-05-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_pregunta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='recomendaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
